### ISSUE TITLE
Circular dependency in `DataResolver`/`GuildTemplate`

### ISSUE THREAD

**Issue by cherryblossom000** [discordjs/discord.js#5600]
**Please describe the problem you are having in as much detail as possible:**

Running the code sample below produces this:

```
❯ node testing.mjs
fetched template
(node:96497) Warning: Accessing non-existent property 'resolveImage' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:96497) UnhandledPromiseRejectionWarning: TypeError: DataResolver.resolveImage is not a function
    at GuildTemplate.createGuild (/path/to/node_modules/.pnpm/github.com+discordjs+discord.js@0e40f9b86826ba50aa3840807fb86e1bce6b1c3d/node_modules/discord.js/src/structures/GuildTemplate.js:110:34)
    at Client.<anonymous> (file:///path/to/testing.mjs:10:34)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:96497) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:96497) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
^C
```

The error occurs because `DataResolver` requires `GuildTemplate`, which requires `DataResolver`. `DataResolver.resolveImage` is called in `GuildTemplate#createGuild`, which is `undefined` due to the circular dependency.

I believe this was introduced in https://github.com/discordjs/discord.js/pull/5384/files#diff-919bb374deac8ecaa94a5d6f70403ba5e0287487076c056028491697f58d4606R8.

**Include a reproducible code sample here, if possible:**

```js
import {Client} from 'discord.js'

const templateCode = 'some valid template code'

const client = new Client({intents: ['GUILDS']})
client
  .on('ready', async () => {
    const template = await client.fetchGuildTemplate(templateCode)
    console.log('fetched template')
    const guild = await template.createGuild('guild name')
    console.log('created guild')
    await guild.delete()
    console.log('deleted guild')
  })
  .login('token')
  .catch(console.error)
```

**Further details:**

- discord.js version: master (0e40f9b86826ba50aa3840807fb86e1bce6b1c3d)
- Node.js version: 14.15.4
- Operating system: macOS 11.3.1
- Priority this issue should have – please be realistic and elaborate if possible: high

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

- I have also tested the issue on latest master, commit hash: 0e40f9b86826ba50aa3840807fb86e1bce6b1c3d
