### ISSUE TITLE
Presence Typing Missing in ClientUser

### ISSUE THREAD

**Issue by Butterstroke** [discordjs/discord.js#6460]
**Please describe the problem you are having in as much detail as possible:**

When trying to get the current presence for my bot through the client, the TSLint errors with a `Property 'presence' does not exist on type 'ClientUser'. ts(2339)` message. 
![image](https://user-images.githubusercontent.com/26350892/129625878-603f53dc-99e6-4e7c-bc93-71500fa45daa.png)

However, if I suppress the error with a ts-ignore comment, I can get the presence during runtime with the same code.
![image](https://user-images.githubusercontent.com/26350892/129627588-a2b028c3-0c32-475e-b319-ea6d42e888ce.png)

**Include a reproducible code sample here, if possible:**

```js
export function presenceHelper(
	client: Client,
	name: string,
	type = "play",
	status: PresenceStatusData = "online"
): void {
    // Snip non-relevant code

    let presenceStatus = null;
    if (client.user.presence.activities[0].name !== null) {
        presenceStatus = client.user.presence.activities[0].name;
    }
    // Snip non-relevant code
}
```

**Further details:**
This is a part of my code for v12 and only ran into this when updating to v13. I can't say if this typing issue is recent or older as I'm converting my codebase into TypeScript from JavaScript at the same time. The v13 documentation also lists presence as a read-only property for ClientUser.

- discord.js version: 13.1.0
- Node.js version: 16.6.2
- Operating system: Windows
- TypeScript version: 4.3.5
- Priority this issue should have – please be realistic and elaborate if possible:
Low priority. It's more annoying than code breaking for TypeScript users if you use a ts-ignore for it.

**Comment by xMooddyy** [comment]
Fixed in #6450

**Comment by Butterstroke** [comment]
> Pending fix in PR #6450

Correct me if I'm reading this wrong, but that PR doesn't seem to fix what I was reporting on. The PR only targets `Client.presence` and not `ClientUser.presence`. It is also marked as private so it would be not accessible outside of the class functions.

**Comment by ImRodry** [comment]
That PR does indeed only fix the missing declarations for client. I'll add this as well since it's still in the scope of the PR, thanks!
