### PR TITLE
refactor!: use `AsyncEventEmitter` instead of `EventEmitter`

### LINKED ISSUE #10577: After upgrading @types/node to v22.7.9, an incompatible type error occurs in the “on” method of the client class
### Which package is this bug report for?

discord.js

### Issue description

After upgrading @types/node v22.7.9, the following error occurs when executing the tsc command.

```
node_modules/.pnpm/discord.js@14.16.3/node_modules/discord.js/typings/index.d.ts(986,14): error TS2417: Class static side 'typeof Client' incorrectly extends base class static side 'typeof BaseClient'.
The types returned by 'on(...)' are incompatible between these types.
   Property '[Symbol.asyncDispose]' is missing in type 'AsyncIterableIterator<any>' but required in type 'AsyncIterator<any[], any, any>'.
```

It could be a problem with @types/node, but this type error appears to be occurring in discord.js, so we will raise it here first.

### Code sample

```typescript
https://github.com/jaoafa/discord-new-threads/actions/runs/11490768941/job/31982043563?pr=1179
```

### Versions

- discord.js v14.16.3
- Node.js v20.18.0
- pnpm v9.12.2
- TypeScript 5.6.3

### Issue priority

Medium (should be fixed soon)

### Which partials do you have configured?

Not applicable

### Which gateway intents are you subscribing to?

Not applicable

### I have tested this issue on a development release

_No response_

### PR DESCRIPTION
**Pull request by almeidx**
BREAKING CHANGE: The `BaseClient`, `Shard`, `ShardingManager`, and `Collector` classes now extend `AsyncEventEmitter` instead of `EventEmitter`.

Besides the obvious change, I also renamed `ClientEvents` to `ClientEventTypes` for consistency with the rest of the emitters.

Fixes #10577
Supersedes #10581, and #10584 partially

### CODE REVIEW

**Review by Jiralite — APPROVED** [review]

**Review by kyranet — APPROVED** [review]
🎉

File: packages/discord.js/typings/index.d.ts [hunk 1]
```diff
@@ -2783,26 +2726,6 @@ export class ReactionCollector extends Collector<Snowflake | string, MessageReac
   public collect(reaction: MessageReaction, user: User): Snowflake | string | null;
   public dispose(reaction: MessageReaction, user: User): Snowflake | string | null;
   public empty(): void;
-
-  public on(
```
Comment (Qjuh) [inline packages/discord.js/typings/index.d.ts:2787]: This is now missing the `remove` event in the typings.

File: packages/discord.js/typings/index.d.ts [hunk 2]
```diff
@@ -2783,26 +2726,6 @@ export class ReactionCollector extends Collector<Snowflake | string, MessageReac
...
-    event: 'collect' | 'dispose' | 'remove' | 'ignore',
-    listener: (reaction: MessageReaction, user: User) => void,
-  ): this;
-  public on(
-    event: 'end',
-    listener: (collected: ReadonlyCollection<Snowflake, MessageReaction>, reason: string) => void,
-  ): this;
-  public on(event: string, listener: (...args: any[]) => void): this;
-
-  public once(
```
Comment (Qjuh) [inline packages/discord.js/typings/index.d.ts:2797]: Ditto

File: packages/discord.js/typings/index.d.ts [hunk 3]
```diff
@@ -2031,19 +1987,6 @@ export class InteractionCollector<Interaction extends CollectedInteraction> exte
   public collect(interaction: Interaction): Snowflake;
   public empty(): void;
   public dispose(interaction: Interaction): Snowflake;
-  public on(event: 'collect' | 'dispose' | 'ignore', listener: (interaction: Interaction) => void): this;
```
Comment (Qjuh) [inline packages/discord.js/typings/index.d.ts:2034]: This did set the emitted variables correctly although the `Extras` type parameter in the extends was wrong. There are no extras emitted from this class, they typings were always wrong it seems. Need to remove the `[Collection<Snowflake, Interaction>]` on the extends of this class to be correct again.

**Review by Qjuh — CHANGES_REQUESTED** [review]

**Review by Qjuh — APPROVED** [review]

**Review by vladfrangu — APPROVED** [review]

**Review by iCrawl — APPROVED** [review]

**Review by ckohen — APPROVED** [review]
