### ISSUE TITLE
TypeError: ca.guilds.get is not a function

### ISSUE THREAD

**Issue by ZandercraftGames** [discordjs/discord.js#3802]
**Please describe the problem you are having in as much detail as possible:**
Whenever the bot needs to create an embed message it outputs the following error:
```js
[#########.........] | postinstall:container: WARN discord.js@12.0.0-dev requir [#########.........] | postinstall:container: WARN discord.js@12.0.0-dev requir [#########.........] | postinstall:container: WARN discord.js@12.0.0-dev requir [#########.........] | postinstall:container: WARN discord.js@12.0.0-dev requir [#########.........] | postinstall:container: WARN discord.js@12.0.0-dev requir [#########.........] | postinstall:container: WARN discord.js@12.0.0-dev requir [#########.........] | postinstall:container: WARN discord.js@12.0.0-dev requir [#########.........] | postinstall:container: WARN discord.js@12.0.0-dev requir [#########.........] | postinstall:container: WARN discord.js@12.0.0-dev requir [#########.........] | postinstall:container: WARN discord.js@12.0.0-dev requir [#########.........] | postinstall:container: WARN discord.js@12.0.0-dev requir [#########.........] | postinstall:container: WARN discord.js@12.0.0-dev requir [#########.........] | postinstall:container: WARN discord.js@12.0.0-dev requir [#########.........] | postinstall:container: WARN discord.js@12.0.0-dev requir [#########.........] | postinstall:container: WARN discord.js@12.0.0-dev requir [#########.........] | postinstall:container: WARN discord.js@12.0.0-dev requir /home/container/build/listeners/client/Ready.js:62
ca.guilds.get("207724893347774474").members.forEach((m) => {
TypeError: ca.guilds.get is not a function
at roles (/home/container/build/listeners/client/Ready.js:62:15)
at Timeout.setInterval [as _onTimeout] (/home/container/build/listeners/client/Ready.js:16:27)
at ontimeout (timers.js:436:11)
at tryOnTimeout (timers.js:300:5)
at listOnTimeout (timers.js:263:5)
at Timer.processTimers (timers.js:223:10)
```

**Further details:**
- discord.js version: 12.0.0-dev
- Node.js version: 12.16.0
- Operating system: Ubuntu 19.04 (inside Docker container)
- Priority this issue should have: 7/10 - bot needs to be ready very soon for a server that I am on the IT team for.

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by RDambrosio016** [comment]
Please use the discord for these issues, this is caused by #3696
