### ISSUE TITLE
Slash command builder type incompatibility

### ISSUE THREAD

**Issue by Anonymous4078** [discordjs/discord.js#10256]
### Which package is this bug report for?

discord.js

### Issue description

Even after upgrading to 14.15.2

There are many errors
```js
error TS2375: Type 'SlashCommandOptionsOnlyBuilder' is not assignable to type 'SlashCommandBuilder | SlashCommandSubcommandsOnlyBuilder' with 'exactOptionalPropertyTypes: true'. Consider adding 'undefined' to the types of the target's properties.
````

### Versions

- discord.js 14.15.2
- typescript 5.4.5
- node.js v20.11.0

### Issue priority

High (immediate attention needed)

### Which partials do you have configured?

Not applicable

### Which gateway intents are you subscribing to?

Not applicable

**Comment by monbrey** [comment]
Please provide a reproducible code sample.

**Comment by Anonymous4078** [comment]
```js
data: new SlashCommandBuilder()
        .setName('info')
        .setDescription('View information')
        .addNumberOption((option) =>
          option
            .setName('id')
            .setDescription('Desc')
            .setRequired(true)
            .setMinValue(1),
        )
        .setDMPermission(false),```

**Comment by Jiralite** [comment]
Please at least make an effort to properly title your issues. At a glance, they are not informative.

<hr>

This looks like `data` expects something else—that builder does not reproduce any errors for me. Double-check your `data` please!

**Comment by Anonymous4078** [comment]
> Please at least make an effort to properly title your issues. At a glance, they are not informative.
> 
> This looks like `data` expects something else—that builder does not reproduce any errors for me. Double-check your `data` please!

`public readonly data:
    | SlashCommandBuilder
    | SlashCommandSubcommandsOnlyBuilder;`

**Comment by rbd03** [comment]
> `public readonly data: | SlashCommandBuilder | SlashCommandSubcommandsOnlyBuilder;`

is there meant to be a `|` between `data` and `SlashCommandBuilder`? what I am getting from typescript language server output is `data: (SlashCommandBuilder | SlashCommandOptionsOnlyBuilder)`. perhaps there is a hidden `null`? I'm just guessing, don't really know...
