### ISSUE TITLE
After upgrading @types/node to v22.7.9, an incompatible type error occurs in the “on” method of the client class

### ISSUE THREAD

**Issue by book000** [discordjs/discord.js#10577]
### Which package is this bug report for?

discord.js

### Issue description

After upgrading @types/node v22.7.9, the following error occurs when executing the tsc command.

```
node_modules/.pnpm/discord.js@14.16.3/node_modules/discord.js/typings/index.d.ts(986,14): error TS2417: Class static side 'typeof Client' incorrectly extends base class static side 'typeof BaseClient'.
The types returned by 'on(...)' are incompatible between these types.
   Property '[Symbol.asyncDispose]' is missing in type 'AsyncIterableIterator<any>' but required in type 'AsyncIterator<any[], any, any>'.
```

It could be a problem with @types/node, but this type error appears to be occurring in discord.js, so we will raise it here first.

### Code sample

```typescript
https://github.com/jaoafa/discord-new-threads/actions/runs/11490768941/job/31982043563?pr=1179
```

### Versions

- discord.js v14.16.3
- Node.js v20.18.0
- pnpm v9.12.2
- TypeScript 5.6.3

### Issue priority

Medium (should be fixed soon)

### Which partials do you have configured?

Not applicable

### Which gateway intents are you subscribing to?

Not applicable

**Comment by Renegade334** [comment]
Will currently affect builds using the latest @types/node releases in the following circumstances:

- TS >= 5.6
- esnext.disposable library loaded
- skipLibCheck off

Will look at sorting later.

**Comment by cobaltt7** [comment]
> * esnext.disposable library loaded

I had this same issue, and it was fixed by adding `esnext.disposable` to my `lib`. Looking at the linked repo, it looks like they only have `esnext.asyncdisposable`, which I'm not sure exists.

@book000 Try changing `esnext.asyncdisposable` to `esnext.disposable` in your tsconfig.json `lib`

**Comment by book000** [comment]
@cobaltt7 The following changes have been made, but have not improved the error.

- Pull request: https://github.com/jaoafa/discord-new-threads/pull/1196
- CI log: https://github.com/jaoafa/discord-new-threads/actions/runs/11508694464/job/32037393529?pr=1196

**Comment by JstnMcBrd** [comment]
Just tested on the new `discord.js@14.18.0` release, and the type error is not fixed. Could we reopen this issue?

```json
  "dependencies": {
    "discord.js": "^14.18.0"
  },
  "devDependencies": {
    "@types/node": "^22.13.4"
  },
```

```ts
import * as discord from 'discord.js';
```

```
node_modules/discord.js/typings/index.d.mts:1032:14 - error TS2417: Class static side 'typeof Client' incorrectly extends base class static side 'typeof BaseClient'.
  The types returned by 'on(...)' are incompatible between these types.
    Property '[Symbol.asyncDispose]' is missing in type 'AsyncIterableIterator<any>' but required in type 'AsyncIterator<any[], any, any>'.

1032 export class Client<Ready extends boolean = boolean> extends BaseClient {
                  ~~~~~~

  node_modules/typescript/lib/lib.esnext.disposable.d.ts:40:5
    40     [Symbol.asyncDispose](): PromiseLike<void>;
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    '[Symbol.asyncDispose]' is declared here.


Found 1 error in node_modules/discord.js/typings/index.d.mts:1032
```

**Comment by almeidx** [comment]
It has been fixed only in the v15-dev version. Not sure if the fix I made is backportable to v14.

**Comment by JstnMcBrd** [comment]
Oh, my bad. I forgot this was a breaking change. Just realized it wasn't included in the [14.18.0 changelog](https://github.com/discordjs/discord.js/releases/tag/14.18.0) either. Please disregard.

**Comment by book000** [comment]
Hopefully this will be backported to v14 if possible.
I would not want to work around this by turning on skipLibCheck, as it could cause the application to stop working due to the library.

**Comment by Renegade334** [comment]
It can't be backported; the only question is whether or not an alternative change should be made to the types, although the choice would be between a rather roundabout hack or removing the djs-specific `Client` overloads entirely.
