### ISSUE TITLE
Property 'choices' does not exist on type 'ApplicationCommandOption'

### ISSUE THREAD

**Issue by LOLBRUHNICE** [discordjs/discord.js#6441]
**Please describe the problem you are having in as much detail as possible:**

when I try to access to the property "choices" in opt (defined in the forEach shown in the code sample) , I get the error which is displayed below
Property 'choices' does not exist on type 'ApplicationCommandOption'
only after I update discord.js to v13.1.0, and it works fine at v13.0.1

but when I look at the index.d.ts (typing of discord.js v13.1.0), I see that property choices actually exist in type ApplicationCommandChoicesData, and ApplicationCommandOptionData includes ApplicationCommandChoicesData
, and ApplicationCommandOption includes ApplicationCommandOptionData

(Display properly: ApplicationCommandOption  > ApplicationCommandOptionData > ApplicationCommandChoicesData > choices)

**Include a reproducible code sample here, if possible:**

```js
const command = client.application.commands.cache.find(xxx);
command.options.forEach((opt) => {
    console.log(opt.choices)
})
```

**Further details:**

- discord.js version: v13.1.0
- Node.js version: 16.6.1
- Operating system: windows
- Priority this issue should have – please be realistic and elaborate if possible: high i think

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by ImRodry** [comment]
Can reproduce and this is a direct consequence of #6247 which made it almost impossible to work with command options and typescript. I honestly think that PR should be 100% reverted

**Comment by LOLBRUHNICE** [comment]
It still doesn't solved after I use PR(dev version)

**Comment by suneettipirneni** [comment]
> Can reproduce and this is a direct consequence of #6247 which made it almost impossible to work with command options and typescript. I honestly think that PR should be 100% reverted

Correction: This was actually caused by #6832.

I believe that it would be a step backwards to revert it. Not all commands have an `options` field, trying to access it on an arbitrary command doesn't really make sense. It saying that it doesn't exist is both accurate and intentional. 

When a developer hasn't shown that it's a command that supports options or not then it's safe to assume there are no options at all.

This begs the question of "why not just make it optional?". 

If it's optional people will assume that any kind of command can take options. Again this isn't true, and will result in runtime errors. The essence of typescript is to prevent runtime errors via compiler errors.

In this specific situation, if *you know* that the command supports options you should use a type assertion:

`as ChatInputCommand`

or prefix with `<ChatInputCommand>`

And your code will work.

**Comment by suneettipirneni** [comment]
I'd also like to add that this something the discord-api-types does as well.

**Comment by LOLBRUHNICE** [comment]
discord.js doesn't contain a type named ChatInputCommand

**Comment by suneettipirneni** [comment]
Sorry I meant `ChatInputApplicationCommandData `

**Comment by LOLBRUHNICE** [comment]
it still doesnt fix the problem

**Comment by LOLBRUHNICE** [comment]
and i think it is the problem with the ApplicationCommandOptionData, not command data

**Comment by monbrey** [comment]
This can be typeguarded by checking that the type of option can have the `choices` property, e.g.
```js
command.options.forEach((opt) => {
  if(opt.type === "STRING") {
    console.log(opt.choices)
  }
});
```

**Comment by suneettipirneni** [comment]
> it still doesnt fix the problem

Can you show us the code you're trying?

**Comment by suneettipirneni** [comment]
```ts
const command = client.application.commands.cache.find(command => command.name === 'foo') as ChatInputApplicationCommandData;
command.options.forEach((opt) => {
    console.log(opt.choices)
})
```

I just tried this on my end and it works without any errors

**Comment by LOLBRUHNICE** [comment]
it solved after i add `opt.type === "STRING"` condition

**Comment by LOLBRUHNICE** [comment]
thks for helping me :)

**Comment by suneettipirneni** [comment]
np, checking choice data will be easier when #6410 is merged.
